version: '3.7'

services:
    vhost:
        image: jwilder/nginx-proxy:alpine
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    mongo:
        image: mvertes/alpine-mongo
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db

    tracing-api:
        build: .
        depends_on:
            - mongo
            - vhost
        environment:
            DEBUG: appify:*
            DEEPTRACE_MONGODB_URI: mongodb://mongo:27017/traces
            NODE_ENV: development
            VIRTUAL_HOST: api.deeptrace.*

volumes:
    mongo:
